services:
  card-studio:
    image: card-studio-frontend:latest 
    container_name: card-studio-front-prod

    restart: always
    build:
      context: .
      target: dev
    ports:
      - "8088:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
 
 
